# Generated by Django 3.2.9 on 2021-11-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0002_gamecategory_gamerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_on',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='estimated_time_to_play',
            field=models.CharField(max_length=50),
        ),
    ]
