# Generated by Django 3.2.9 on 2021-11-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0003_auto_20211105_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gameraterapi.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GameCategory',
        ),
    ]
